name: httpd
type: service
icon: httpd
title: Apache HTTP server
scalable: true
hostname: httpd

options:
- version: '2.4'
  tag: 2.4
  default: true

containers:
- name: httpd
  image: wodby/apache

endpoints:
- name: http
  ports:
  - name: http
    number: 80
    type: http
    main: true

configs:
- name: main
  title: Main
  filepath: /etc/gotpl/http.conf.tmpl
  config: httpd.conf.tmpl
- name: vhost
  title: Virtual host
  filepath: /etc/gotpl/vhost.conf.tmpl
  config: vhost.conf.tmpl

labels:
- httpd
- apache

build:
  connect: true
  templates:
  - name: nextjs
    title: Next.js
    repo: https://github.com/wodby/nextjs
    branch: main

settings:
- name: docroot
  title: Apache docroot subdir
  var: DOCROOT_SUBDIR

env:
- name: APACHE_DOCUMENT_ROOT
  value: /var/www/html/$(DOCROOT_SUBDIR)

helm:
  name: wodby
  source: oci://registry-1.docker.io/wodby/httpd
  chart: oci://registry-1.docker.io/wodby/httpd
  version: 0.1.0
  configurations:
  - name: httpd
    labels: commonLabels
    annotations: commonAnnotations
    env: extraEnvVars
    resources: resources
    volumes: extraVolumes
    mounts: extraVolumeMounts
