name: httpd
type: service
icon: httpd
title: Apache HTTP server
scalable: true
hostname: httpd

options:
- version: '2.4'
  tag: 2.4.59-debian-12-r1
  default: true

containers:
- name: httpd
  image: bitnami/apache
  env:
  - name: DISABLE_WELCOME_MESSAGE
    value: 'true'

routes:
- name: http
  ports:
  - name: http
    number: 80
    type: http
    main: true
    ingress: true

labels:
- httpd
- apache

build:
  connect: true
  templates:
  - name: nextjs
    title: Next.js
    repo: https://github.com/wodby/nextjs
    branch: main

settings:
- name: docroot
  title: Apache docroot subdir
  var: DOCROOT_SUBDIR

env:
- name: APACHE_DOCUMENT_ROOT
  value: /var/www/html/$(DOCROOT_SUBDIR)

  
helm:
  name: bitnami
  source: oci://registry-1.docker.io/bitnamicharts/apache
  chart: oci://registry-1.docker.io/bitnamicharts/apache
  version: 11.0.2
  configurations:
  - name: apache
    labels: commonLabels
    annotations: commonAnnotations
    env: extraEnvVars
    resources: resources
  values:
  - name: resourcesPreset
    value: 'none'
  
